spring.application.name=Sang et Or Social

#BDD
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
logging.level.org.hibernate.orm.jdbc.bind=trace

jwt.secret=my-very-long-super-secure-secret-key-123456
jwt.expiration=360000
