spring.application.name=Sang et Or Social

#BDD
# Database connection
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=mysecretpassword
spring.datasource.driver-class-name=org.postgresql.Driver
# Connection pool settings (HikariCP is default)
spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.max-lifetime=1800000
spring.datasource.hikari.connection-timeout=20000
# Hibernate JPA Settings
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
logging.level.com.zaxxer.hikari=ERROR
logging.level.org.hibernate=ERROR
logging.level.org.hibernate.orm.jdbc.bind=trace
# Connection pool settings for HikariCP
spring.datasource.hikari.auto-commit=true
spring.datasource.hikari.transaction-isolation=TRANSACTION_READ_COMMITTED
spring.datasource.hikari.connection-test-query=SELECT 1


# SECURITY
# The secret key must be an HMAC hash string of 256 bits; otherwise, the token generation will throw an error.
# Website used to generate it : https://www.devglan.com/online-tools/hmac-sha256-online
jwt.secret=3cfa76ef14937c1c0ea519f8fc057a80fcd04a7420f8e8bcd0a7567c272e007b
# The token expiration time is expressed in milliseconds.
jwt.expiration=3600000

# ----------------------------
# Flyway Configuration
# ----------------------------
# Enables Flyway database migrations at application startup.
# Explicit for clarity, even though the Flyway starter enables it by default.
spring.flyway.enabled=true
# Location where Flyway looks for migration scripts.
# By convention: src/main/resources/db/migration
spring.flyway.locations=classpath:db/migration
# It is a convenience instead of running a separate baseline step
# for initial Flyway production deployments on projects with an existing DB.
spring.flyway.baselineOnMigrate=true